name: 'publish-zauth'
run-name: action triggered by @${{ github.actor }}

on: [push]

jobs:
  publish-zauth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ZAuth
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.11.0
